### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by 18954534983** [uestc-icsp/VoxelMapPlus_Public#2]
你好，我在编译时总会报下面的错误，请问怎么解决呢？

Base path: /home/k/catkin_voxelmapplus
Source space: /home/k/catkin_voxelmapplus/src
Build space: /home/k/catkin_voxelmapplus/build
Devel space: /home/k/catkin_voxelmapplus/devel
Install space: /home/k/catkin_voxelmapplus/install
####
####
####
####
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  6%] Building CXX object VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/src/voxelMapping.cpp.o
c++: error: 2: 没有那个文件或目录
VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/build.make:62: recipe for target 'VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/src/voxelMapping.cpp.o' failed
make[2]: *** [VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/src/voxelMapping.cpp.o] Error 1
CMakeFiles/Makefile2:696: recipe for target 'VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/all' failed
make[1]: *** [VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[  6%] Built target geometry_msgs_generate_messages_py
[  6%] Built target _voxel_map_plus_generate_messages_check_deps_States
[  6%] Built target _voxel_map_plus_generate_messages_check_deps_Pose6D
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by Sunnystaste** [comment]
[ 6%] Building CXX object VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/src/voxelMapping.cpp.o
c++: error: 2: 没有那个文件或目录
应该是环境配置的问题吧，我暂时也没看明白

**Comment by lizhuo1414** [comment]
> 你好，我在编译时总会报下面的错误，请问怎么解决呢？
> 
> Base path: /home/k/catkin_voxelmapplus Source space: /home/k/catkin_voxelmapplus/src Build space: /home/k/catkin_voxelmapplus/build Devel space: /home/k/catkin_voxelmapplus/devel Install space: /home/k/catkin_voxelmapplus/install
> 
> #### Running command: "make cmake_check_build_system" in "/home/k/catkin_voxelmapplus/build"
> #### Running command: "make -j4 -l4" in "/home/k/catkin_voxelmapplus/build"
> [ 0%] Built target geometry_msgs_generate_messages_nodejs [ 6%] Building CXX object VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/src/voxelMapping.cpp.o c++: error: 2: 没有那个文件或目录 VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/build.make:62: recipe for target 'VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/src/voxelMapping.cpp.o' failed make[2]: *** [VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/src/voxelMapping.cpp.o] Error 1 CMakeFiles/Makefile2:696: recipe for target 'VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/all' failed make[1]: *** [VoxelMapPlus_Public/CMakeFiles/voxel_mapping_plus_odom.dir/all] Error 2 make[1]: *** 正在等待未完成的任务.... [ 6%] Built target geometry_msgs_generate_messages_py [ 6%] Built target _voxel_map_plus_generate_messages_check_deps_States [ 6%] Built target _voxel_map_plus_generate_messages_check_deps_Pose6D Makefile:140: recipe for target 'all' failed make: *** [all] Error 2 Invoking "make -j4 -l4" failed

It`s a CMakelists.txt bug from VoxelMap. check this out.
https://github.com/hku-mars/VoxelMap/issues/5#issuecomment-1181313914
