### ISSUE TITLE
三种激光头在SLAM应用中的鲁棒性不一

### ISSUE THREAD

**Issue by jiawenquan** [uestc-icsp/VoxelMapPlus_Public#3]
三种激光头在SLAM应用中的鲁棒性不一，与Fast LIO2进行了对比。

Hesai XT32:
	•	鲁棒性优秀，表现出色。
Ouster 32线 & Mid360:
	•	鲁棒性差。
	•	与Fast LIO2对比，无法完成有效建图。

希望作者能对Ouster 32线和Mid360进行优化适配。疑似问题源于噪音协方差。Hesai XT32的表现可作为参考。

**Comment by James-0911** [comment]
> 三种激光头在SLAM应用中的鲁棒性不一，与Fast LIO2进行了对比。
> 
> Hesai XT32: • 鲁棒性优秀，表现出色。 Ouster 32线 & Mid360: • 鲁棒性差。 • 与Fast LIO2对比，无法完成有效建图。
> 
> 希望作者能对Ouster 32线和Mid360进行优化适配。疑似问题源于噪音协方差。Hesai XT32的表现可作为参考。

你好，你也是自己的数据跑的嘛，我用hesai跑的，很容易就跑飞了

**Comment by jiawenquan** [comment]
> > 三种激光头在SLAM应用中的鲁棒性不一，与Fast LIO2进行了对比。
> 
> > 
> 
> > Hesai XT32: • 鲁棒性优秀，表现出色。 Ouster 32线 & Mid360: • 鲁棒性差。 • 与Fast LIO2对比，无法完成有效建图。
> 
> > 
> 
> > 希望作者能对Ouster 32线和Mid360进行优化适配。疑似问题源于噪音协方差。Hesai XT32的表现可作为参考。
> 
> 
> 
> 你好，你也是自己的数据跑的嘛，我用hesai跑的，很容易就跑飞了

需要修改适配hesai 激光头，时间戳赋值

**Comment by James-0911** [comment]
> > > 三种激光头在SLAM应用中的鲁棒性不一，与Fast LIO2进行了对比。
> > 
> > 
> > > 
> > 
> > 
> > > Hesai XT32: • 鲁棒性优秀，表现出色。 Ouster 32线 & Mid360: • 鲁棒性差。 • 与Fast LIO2对比，无法完成有效建图。
> > 
> > 
> > > 
> > 
> > 
> > > 希望作者能对Ouster 32线和Mid360进行优化适配。疑似问题源于噪音协方差。Hesai XT32的表现可作为参考。
> > 
> > 
> > 你好，你也是自己的数据跑的嘛，我用hesai跑的，很容易就跑飞了
> 
> 需要修改适配hesai 激光头，时间戳赋值

嗯嗯，修改了的，跑稍微长一点的数据就飞了，应该是噪声设置问题

**Comment by Sunnystaste** [comment]
可能是3DOF的理论部分存在一些缺陷：
d的物理意义是截距，它的不确定度会因平面距原点的变远而变大，最后传导到测量方差R上，导致系统更信赖接近原点的平面。
表现就是跑稍微长一点的数据就飞了hhh。

**Comment by James-0911** [comment]
> 可能是3DOF的理论部分存在一些缺陷： d的物理意义是截距，它的不确定度会因平面距原点的变远而变大，最后传导到测量方差R上，导致系统更信赖接近原点的平面。 表现就是跑稍微长一点的数据就飞了hhh。

那这个有办法改进吗，你说的3DOF是指论文中的哪部分

**Comment by Sunnystaste** [comment]
> > 可能是3DOF的理论部分存在一些缺陷： d的物理意义是截距，它的不确定度会因平面距原点的变远而变大，最后传导到测量方差R上，导致系统更信赖接近原点的平面。 表现就是跑稍微长一点的数据就飞了hhh。
> 
> 那这个有办法改进吗，你说的3DOF是指论文中的哪部分

3DOF指的是平面的协方差。目前在Private仓库下构思改进方案，尝试把法向量的不确定度和距离的不确定度分开。

**Comment by zhujinwen0924** [comment]
Good Job!!!
