### ISSUE TITLE
运行Livox HAP数据集跑飞

### ISSUE THREAD

**Issue by KevinJohnsonL** [uestc-icsp/VoxelMapPlus_Public#7]
非常感谢你的开源贡献！在默认参数下跑了提供的室内退化场景下的数据集，每次跑到大概180秒就跑飞，如图所示。
请问可能是参数问题还是不确定度累计导致的？
![drift_voxel_map++](https://github.com/uestc-icsp/VoxelMapPlus_Public/assets/41880024/9df7b381-d75f-4a7e-9db1-0871f261744d)

**Comment by DAIF1984** [comment]
I met the same problem,It's very easy to diverge around corners

**Comment by Sunnystaste** [comment]
稳定性有问题，3DOF估计的时候把截距拿进来了。
导致协方差不稳定..线性展开之后近似高斯分布的假设就不成立了。
导致播包的时候，稍微I/O稍微有点不一样就容易飞。
